# Generated by Django 2.2.7 on 2019-11-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_disc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
